sector_portfolios = {
    "BANKING_FINANCE": [
        "HDFCBANK.NS", "ICICIBANK.NS", "KOTAKBANK.NS", "AXISBANK.NS",
        "SBIN.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "HDFC.NS",
        "INDUSINDBK.NS", "BAJAJHLDNG.NS", "SBILIFE.NS", "HDFCLIFE.NS",
    ],
    "IT": ["TCS.NS", "INFY.NS", "WIPRO.NS", "HCLTECH.NS", "TECHM.NS"],
    "ENERGY": ["RELIANCE.NS", "ONGC.NS", "IOC.NS"],
    "CONSUMER": ["ITC.NS", "NESTLEIND.NS", "BRITANNIA.NS", "TITAN.NS", "ULTRACEMCO.NS"],
    "AUTO": ["MARUTI.NS", "M&M.NS", "TATAMOTORS.NS", "EICHERMOT.NS"],
    "HEALTHCARE": ["SUNPHARMA.NS", "DRREDDY.NS", "CIPLA.NS", "DIVISLAB.NS"],
    "TELECOM": ["BHARTIARTL.NS"],
    "METALS": ["TATASTEEL.NS", "HINDALCO.NS"],
    "INFRA": ["LT.NS", "ADANIPORTS.NS", "GRASIM.NS"],
    "OTHERS": ["ASIANPAINT.NS", "POWERGRID.NS", "NTPC.NS"],
    "INDICES": ["^NSEI", "^BSESN"],
}
